site_name: Hierarchical AI Assistants System - FastAPI Backend
site_description: FastAPI backend documentation using mkdocstrings
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      media: "(prefers-color-scheme: light)"
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
      media: "(prefers-color-scheme: dark)"
  features:
    - navigation.expand
    - navigation.instant
    - navigation.top
    - navigation.footer
    - content.code.annotate
    - content.tabs.link
  language: en

nav:
  - Home: index.md
  - Entry point:
      - Main: entrypoint/main.md
      - App: entrypoint/app.md
  - Routes:
      - Auth:
          - Module: routes/auth/__init__.md
          - Sign-up: routes/auth/sign_up.md
          - Sign-in: routes/auth/sign_in.md
  - Schemas:
      - Auth:
          - Module: schemas/auth/__init__.md
          - Sign-up: schemas/auth/sign_up.md
          - Sign-in: schemas/auth/sign_in.md
  - Tests:
      - Schemas:
          - Sign-up: tests/schemas/auth/sign_up.md
          - Sign-in: tests/schemas/auth/sign_in.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_toc_entry: true
            show_root_heading: true
            heading_level: 2
            filters:
              - "!^_"
  - autorefs

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
