site_name: Hierarchical AI Assistants System - FastAPI Backend
site_description: FastAPI backend documentation using mkdocstrings
site_url: https://twoja-domena.pl
theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.annotate
    - content.tabs.link
  language: en

nav:
  - Home: index.md
  - Routes:
      - Auth:
          - Register: routes/auth/register.md
  - Schemas:
      - Auth:
          - Register form: schemas/auth/register.md
  - Tests:
      - Routes:
          - Register route: tests/routes/auth/register.md
      - Schemas:
          - Register form: tests/schemas/auth/register.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: false
            show_root_toc_entry: true
            show_root_heading: true
            heading_level: 2
            filters:
              - "!^_"
  - autorefs

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - tables
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
